### ISSUE TITLE
Library "dune.configurator" not found

### ISSUE THREAD

**Issue by yurivict** [rdicosmo/parmap#105]
Version 1.2.3 fails:
```
dune build @install 
File "config/dune", line 3, characters 12-29:
3 |  (libraries dune.configurator))
                ^^^^^^^^^^^^^^^^^
Error: Library "dune.configurator" not found.
```

I have ocaml-4.12.0 and ocaml-dune-2.9.0 installed.

OS: FreeBSD 13

**Comment by UnixJunkie** [comment]
I guess you are not trying to install parmap via its opam package.

From the parmap.opam file:
```
depends: [
  "dune" {>= "2.7"}
  "dune-configurator"
  "base-bigarray"
  "base-unix"
  "ocaml" {>= "4.03.0"}
  "odoc" {with-doc}
]
```
So, an ocaml package called dune-configurator must be installed on the system (among others).

As a workaround, try to install all ocaml software using opam (even the compiler); especially
if your distribution doesn't have all ocaml software and libraries packaged (I guess only Debian
tries to do that).

**Comment by yurivict** [comment]
No, I work on updating of the FreeBSD OCaml ports, so opam wouldn't work.

I have already figured this out: dune has some libraries bundled with it, including ```dune-configurator```.
So it should be built with these libraries included. And there's also a circular dependency that dune depends on one package that in turn depends on dune.

**Comment by yurivict** [comment]
Thank you.
