### ISSUE TITLE
exception handling in child processes

### ISSUE THREAD

**Issue by mlin** [rdicosmo/parmap#13]
Parmap would be more useful for server-side and daemon applications if it had better handling of exceptions raised in child processes. In such applications, errors must be handled promptly, and the show must go on!

An exception in a worker should cause the parallel computation to stop ASAP, and an informative exception raised to the caller. This is understandably tricky due to [lack of exception marshalling](http://caml.inria.fr/mantis/view.php?id=1961), but there are better things to do than panic and exit. 

Some example semantics that might be worth evaluating are in my [ForkWork](http://mlin.github.com/forkwork/ForkWork.html) library. See particularly the paragraph starting "If a child process ends with an exception...", the fail_fast option, and the ChildExn discussion.

**Comment by UnixJunkie** [comment]
my library parany has a fun behavior too: a crashing process creates an infinite loop since the master process will wait the child forever

**Comment by UnixJunkie** [comment]
@mlin developped his own library (forkwork) to handle this case, so I am closing this.
Personally, I think that you should create a mapper withe type ('a -> 'b option) or maybe a result type and a more complete error description instead of None, and catch
all possible exceptions yourself.
