### ISSUE TITLE
mandel_sdl compilation on os x

### ISSUE THREAD

**Issue by nilsbecker** [rdicosmo/parmap#33]
hi, i had to do a little work to get the sdl example to compile on os x. brew install sdl sdl_gfx sdl_image (although i don't know if the latter are necessary). then for the compilation, after some googling, i had to add

    -ccopt "-framework CoreFoundation -framework Cocoa" 

to the mandels_sdl.native target in the Makefile. it does run, and a lot faster than the pure Ocaml version. maybe this could be added?

**Comment by rdicosmo** [comment]
Thanks for working on this...

The simplest way to contribute back your findings would be to add
a file Makefile.OSX to the example directory, containing exactly
the modification you needed to compile properly on OS X.

May you do this and create a pull request?


On Fri, Feb 27, 2015 at 02:41:49PM -0800, nilsbecker wrote:
> hi, i had to do a little work to get the sdl example to compile on os x. brew
> install sdl sdl_gfx sdl_image (although i don't know if the latter are
> necessary). then for the compilation, after some googling, i had to add
> 
> -ccopt "-framework CoreFoundation -framework Cocoa"
> 
> to the mandels_sdl.native target in the Makefile. maybe this could be added?
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Roberto
