### ISSUE TITLE
Cooperation with job submission systems

### ISSUE THREAD

**Issue by elfring** [rdicosmo/parmap#35]
There are some task execution environments available to which data processing can be delegated.
How do you think about to extend your library so that more processors and also remote computing resources can be reused?
Would you like to improve [job submission possibilities](https://en.wikipedia.org/wiki/Job_Submission_Description_Language)?

**Comment by UnixJunkie** [comment]
Parmap is about parallel programming, not distributed.
For distributed programming in OCaml, you can have a look at the Functory or ocamlnet libraries.

**Comment by elfring** [comment]
I imagine that this software library can use special application programming interfaces so that more parallel data processing will become possible.
How do you think to cooperate also with job submission systems for distributed computing?
Can the task execution provider be made configurable?

**Comment by UnixJunkie** [comment]
I think this issue should be closed.

**Comment by elfring** [comment]
Why? - Can the mentioned details be still clarified?

**Comment by UnixJunkie** [comment]
I think this issue should be closed.

**Comment by elfring** [comment]
🔮 How are the chances for a more constructive software development dialogue?
