### ISSUE TITLE
we should have a make test target

### ISSUE THREAD

**Issue by UnixJunkie** [rdicosmo/parmap#39]

**Comment by rdicosmo** [comment]
There is a target tests

**Comment by UnixJunkie** [comment]
I was meaning: something to launch regression tests and easily see if something is broken.

**Comment by rdicosmo** [comment]
Yes, that would be cool... the programs built by make tests are meant to
uncover known issues, but checking their output w.r.t. a reference is not
implemented yet.

2016-04-27 10:59 GMT+02:00 Francois Berenger <notifications@github.com>:

> I was meaning: something to launch regression tests and easily see if
> something is broken.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rdicosmo/parmap/issues/39#issuecomment-215017674>
>



-- 
Roberto Di Cosmo

------------------------------------------------------------------
Professeur (on leave at/detache a INRIA Roquencourt)
IRIF                           email : roberto@dicosmo.org
Universite Paris Diderot         web : http://www.dicosmo.org
Case 7014                    Twitter : http://twitter.com/rdicosmo
5, Rue Thomas Mann
F-75205 Paris Cedex 13 FRANCE
------------------------------------------------------------------
Office location:

Paris Diderot                       INRIA

Bureau 3020 (3rd floor)             Bureau C123
Batiment Sophie Germain             Batiment C
8 place Aurélie Nemours             2, Rue Simone Iff
Tel: +33 1 57 27 92 20              Tel: +33 1 80 49 44 42

Metro
 Bibliotheque F. Mitterrand        Ligne 6: Dugommier
 ligne 14/RER C                    Ligne 14/RER A: Gare de Lyon
------------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3
