### ISSUE TITLE
round up

### ISSUE THREAD

**Issue by JuliaLawall** [rdicosmo/parmap#47]
It seems that parmap rounds down when statically distributing tasks to cores.  For example, I have 284 tasks and 48 cores, which gives 47 cores with 5 tasks each and one core with 49.  This represents a pretty massive hit on the benefits of parallelism.  Giving 6 tasks to most cores would be a big performance improvement.  Everything is fine with ~chunksize:1, but the need for this may not be obvious to most users.

**Comment by UnixJunkie** [comment]
I think chunksize=1 should be the default

**Comment by UnixJunkie** [comment]
everybody wants automatic load balancing to be the default. People who know which chunksize to use should really know what they are doing.

**Comment by UnixJunkie** [comment]
I think most users would benefit from this small little change

**Comment by UnixJunkie** [comment]
I am closing this because there is a workaround. But I agree that the current behavior is sub optimal.
It would have been nice if there was a pull request to implement the suggested change.
