### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by JuliaLawall** [rdicosmo/parmap#51]
Is there anything that flushes or closes stdout when using Parmap.redirect?  I have the impression that my stderr files are complete, but my stdout files are not.
Are there examples of using redirect properly?

**Comment by rdicosmo** [comment]
Hmmm... in principle OCaml flushes a channel before
closing it, so all your files should be complete, but
just in case, try add a flush_all() before this line
https://github.com/rdicosmo/parmap/blob/master/parmap.ml#L250

And see if this changes the result

On Mon, Jan 02, 2017 at 05:08:03AM -0800, JuliaLawall wrote:
> Is there anything that flushes or closes stdout when using Parmap.redirect? I
> have the impression that my stderr files are complete, but my stdout files are
> not.
> Are there examples of using redirect properly?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur (on leave at/detache a INRIA Roquencourt)
IRIF                          E-mail : roberto@dicosmo.org
Universite Paris Diderot         Web : http://www.dicosmo.org
Case 7014                    Twitter : http://twitter.com/rdicosmo         
5, Rue Thomas Mann       
F-75205 Paris Cedex 13 France  
------------------------------------------------------------------
Office location:

Paris Diderot	 		    INRIA
 
Bureau 3020 (3rd floor)             Bureau C123
Batiment Sophie Germain             Batiment C
8 place Aurélie Nemours             2, Rue Simone Iff
Tel: +33 1 57 27 92 20              Tel: +33 1 80 49 44 42 

Metro
  Bibliotheque F. Mitterrand        Ligne 6: Dugommier
  ligne 14/RER C                    Ligne 14/RER A: Gare de Lyon
------------------------------------------------------------------                                                 
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by JuliaLawall** [comment]
On Mon, 2 Jan 2017, Roberto Di Cosmo wrote:

> Hmmm... in principle OCaml flushes a channel before
> closing it, so all your files should be complete, but
> just in case, try add a flush_all() before this line
> https://github.com/rdicosmo/parmap/blob/master/parmap.ml#L250
>
> And see if this changes the result

I made the change and then the standard output looked better, but then I
unmade the change and the standard output still looked better.  So perhaps
the problem was just that I had an out of date version of parmap in teh
first place, and no change is needed.

thanks,
julia

**Comment by rdicosmo** [comment]
Ok, great to know, and happy new year! :-)

On Mon, Jan 02, 2017 at 06:34:06AM -0800, JuliaLawall wrote:
> 
> 
> On Mon, 2 Jan 2017, Roberto Di Cosmo wrote:
> 
> > Hmmm... in principle OCaml flushes a channel before
> > closing it, so all your files should be complete, but
> > just in case, try add a flush_all() before this line
> > https://github.com/rdicosmo/parmap/blob/master/parmap.ml#L250
> >
> > And see if this changes the result
> 
> I made the change and then the standard output looked better, but then I
> unmade the change and the standard output still looked better. So perhaps
> the problem was just that I had an out of date version of parmap in teh
> first place, and no change is needed.
> 
> thanks,
> julia
> 
> 
> >
> > On Mon, Jan 02, 2017 at 05:08:03AM -0800, JuliaLawall wrote:
> > > Is there anything that flushes or closes stdout when using
> > Parmap.redirect? I
> > > have the impression that my stderr files are complete, but my stdout files
> > are
> > > not.
> > > Are there examples of using redirect properly?
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub, or mute the thread.*
> > >
> >
> > --
> > Roberto Di Cosmo
> >
> > ------------------------------------------------------------------
> > Professeur (on leave at/detache a INRIA Roquencourt)
> > IRIF E-mail : roberto@dicosmo.org
> > Universite Paris Diderot Web : http://www.dicosmo.org
> > Case 7014 Twitter : http://twitter.com/rdicosmo
> > 5, Rue Thomas Mann
> > F-75205 Paris Cedex 13 France
> > ------------------------------------------------------------------
> > Office location:
> >
> > Paris Diderot INRIA
> >
> > Bureau 3020 (3rd floor) Bureau C123
> > Batiment Sophie Germain Batiment C
> > 8 place Aurélie Nemours 2, Rue Simone Iff
> > Tel: +33 1 57 27 92 20 Tel: +33 1 80 49 44 42
> >
> > Metro
> > Bibliotheque F. Mitterrand Ligne 6: Dugommier
> > ligne 14/RER C Ligne 14/RER A: Gare de Lyon
> > ------------------------------------------------------------------
> > GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the
> > thread.[AAesmgsH0gTjkjBjvTavYKnmLcUEx9AWks5rOPh8gaJpZM4LZAFH.gif]
> >
> >
> >
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur (on leave at/detache a INRIA Roquencourt)
IRIF                          E-mail : roberto@dicosmo.org
Universite Paris Diderot         Web : http://www.dicosmo.org
Case 7014                    Twitter : http://twitter.com/rdicosmo         
5, Rue Thomas Mann       
F-75205 Paris Cedex 13 France  
------------------------------------------------------------------
Office location:

Paris Diderot	 		    INRIA
 
Bureau 3020 (3rd floor)             Bureau C123
Batiment Sophie Germain             Batiment C
8 place Aurélie Nemours             2, Rue Simone Iff
Tel: +33 1 57 27 92 20              Tel: +33 1 80 49 44 42 

Metro
  Bibliotheque F. Mitterrand        Ligne 6: Dugommier
  ligne 14/RER C                    Ligne 14/RER A: Gare de Lyon
------------------------------------------------------------------                                                 
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by UnixJunkie** [comment]
this can be closed

**Comment by UnixJunkie** [comment]
this still can be closed ;)
