### ISSUE TITLE
ocamldoc doesn't show up in ocp-browser

### ISSUE THREAD

**Issue by UnixJunkie** [rdicosmo/parmap#60]
we might need to install the .cmt  and .cmti files

**Comment by UnixJunkie** [comment]
the ocamldoc hosted in there
https://rdicosmo.github.io/parmap/doc/
is out of date too.

**Comment by UnixJunkie** [comment]
I don't know ocamlbuild so I cannot help with that, but having the doc showing up in ocp-browser is really nice for users.

**Comment by UnixJunkie** [comment]
if there is any Makefile hacker around, your help would be greatly appreciated with this issue (I know almost nothing about makefiles since I have been using Makefile-generating software for years)

**Comment by UnixJunkie** [comment]
If we were using dune, we would not have this problem.
https://github.com/rdicosmo/parmap/issues/40

**Comment by rdicosmo** [comment]
This is now solved, as we moved to dune.
