### ISSUE TITLE
we depend on automake

### ISSUE THREAD

**Issue by UnixJunkie** [rdicosmo/parmap#61]
aclocal is provided by automake.
So parmap (the opam package) fails to install in case we don't have automake installed.
So we need a conf-automake package first ...

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/opam-repository/pull/9568

**Comment by UnixJunkie** [comment]
I'll send an update to the opam package after that one is accepeted

**Comment by rdicosmo** [comment]
Thanks Francois!

On Tue, Jun 20, 2017 at 07:35:37PM -0700, Francois BERENGER wrote:
> I'll send an update to the opam package after that one is accepeted
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto

**Comment by UnixJunkie** [comment]
related to https://github.com/rdicosmo/parmap/pull/65
