### ISSUE TITLE
META linkopts

### ISSUE THREAD

**Issue by barakeel** [rdicosmo/parmap#62]
Ocamlbuild singlequotes the value of linkopts in the META file, making the subsequent calls to ocamlmktop fails.  ocamlmktop '-cclib ...'

linkopts(byte) = "-cclib -lparmap_stubs" 

should be replaced by:

linkopts(byte) += "-cclib"
linkopts(byte) += "-lparmap_stubs"

**Comment by rdicosmo** [comment]
Thanks Thibaut,
   would you mind making a pull request?

On Mon, Oct 23, 2017 at 03:30:24PM +0000, Thibault Gauthier wrote:
> Ocamlbuild singlequotes the value of linkopts in the META file, making the
> subsequent calls to ocamlmktop fails. ocamlmktop '-cclib ...'
> 
> linkopts(byte) = "-cclib -lparmap_stubs"
> 
> should be replaced by:
> 
> linkopts(byte) += "-cclib"
> linkopts(byte) += "-lparmap_stubs"
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur (on leave at/detache a INRIA)
IRIF                          E-mail : roberto@dicosmo.org
Universite Paris Diderot         Web : http://www.dicosmo.org
Case 7014                    Twitter : http://twitter.com/rdicosmo         
5, Rue Thomas Mann       
F-75205 Paris Cedex 13 France  
------------------------------------------------------------------
Office location:

Paris Diderot                       INRIA
 
Bureau 3020 (3rd floor)             Bureau C123
Batiment Sophie Germain             Batiment C
8 place Aurélie Nemours             2, Rue Simone Iff
                                    Tel: +33 1 80 49 44 42 

Metro
  Bibliotheque F. Mitterrand        Ligne 6: Dugommier
  ligne 14/RER C                    Ligne 14/RER A: Gare de Lyon
------------------------------------------------------------------                                                 
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by UnixJunkie** [comment]
the PR that @barakeel should have sent
https://github.com/rdicosmo/parmap/pull/87

**Comment by UnixJunkie** [comment]
@barakeel how can I test that your proposed change is correct?
What is the sequence of commands to reproduce the observed problem?
