### ISSUE TITLE
parmap doesn't compile with OCaml 4.06.0

### ISSUE THREAD

**Issue by UnixJunkie** [rdicosmo/parmap#70]
#=== ERROR while installing parmap.1.0-rc8 ====================================#
    # opam-version 1.2.2
    # os           linux
    # command      make DESTDIR=/home/travis/.opam/4.06.0 OCAMLLIBDIR=lib
    # path         /home/travis/.opam/4.06.0/build/parmap.1.0-rc8
    # compiler     4.06.0
    # exit-code    2
    # env-file     /home/travis/.opam/4.06.0/build/parmap.1.0-rc8/parmap-15223-c1bafb.env
    # stdout-file  /home/travis/.opam/4.06.0/build/parmap.1.0-rc8/parmap-15223-c1bafb.out
    # stderr-file  /home/travis/.opam/4.06.0/build/parmap.1.0-rc8/parmap-15223-c1bafb.err
    ### stdout ###
    # [...]
    # Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
    # File "bytearray.ml", line 41, characters 0-116:
    # Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
    # File "bytearray.ml", line 47, characters 10-23:
    # Warning 3: deprecated: String.create
    # Use Bytes.create instead.
    # File "bytearray.ml", line 48, characters 28-29:
    # Error: This expression has type bytes but an expression was expected of type
    #          string
    # Command exited with code 2.

**Comment by UnixJunkie** [comment]
Sorry, we need a new release in opam.
That's just the version in opam that doesn't compile with 4.06.0.

**Comment by UnixJunkie** [comment]
@rdicosmo Roberto, can you create a new tag? I'd like to update the opam package.
Thanks,
F.

**Comment by rdicosmo** [comment]
Will do soon :-)

On Mon, Feb 19, 2018 at 01:16:56AM +0000, Francois BERENGER wrote:
> @rdicosmo Roberto, can you create a new tag? I'd like to update the opam
> package.
> Thanks,
> F.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Computer Science Professor
            (on leave at INRIA from IRIF/University Paris Diderot)

Software Heritage             E-mail : roberto@dicosmo.org        
INRIA			         Web : http://www.dicosmo.org     
Bureau C123		     Twitter : http://twitter.com/rdicosmo
2, Rue Simone Iff                Tel : +33 1 80 49 44 42
CS 42112
75589 Paris Cedex 12
------------------------------------------------------------------                                                 
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by rdicosmo** [comment]
done :-)


Roberto Di Cosmo

------------------------------------------------------------------
Computer Science Professor
           (on leave at INRIA from IRIF/University Paris Diderot)

Software Heritage             E-mail : roberto@dicosmo.org
INRIA                            Web : http://www.dicosmo.org
Bureau C123                  Twitter : http://twitter.com/rdicosmo
2, Rue Simone Iff                Tel : +33 1 80 49 44 42
CS 42112
75589 Paris Cedex 12
------------------------------------------------------------------

GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

2018-02-19 10:05 GMT+01:00 Roberto Di Cosmo <roberto@dicosmo.org>:

**Comment by UnixJunkie** [comment]
CI tests underway there:
https://github.com/ocaml/opam-repository/pull/11467
