### ISSUE TITLE
bug: gross error in Parmap.array_parmapi

### ISSUE THREAD

**Issue by UnixJunkie** [rdicosmo/parmap#74]
```
 #require "parmap";;
Parmap.array_parmapi ~ncores:2 ~chunksize:1 (fun i x -> (i, x)) [|0;1;2;3;4;5;6;7;8;9|];;
- : (int * int) array =
[|(0, 8); (0, 6); (0, 4); (0, 3); (0, 1); (0, 0); (0, 9); (0, 7); (0, 5);
  (0, 2)|]
```

**Comment by UnixJunkie** [comment]
i should not stay constant and equal to 0

**Comment by UnixJunkie** [comment]
The output should look more like this:
```
Parmap.parmapi ~ncores:2 ~chunksize:1 (fun i x -> (i, x)) (Parmap.L [0;1;2;3;4;5;6;7;8;9]);;
- : (int * int) list =
[(8, 8); (6, 6); (4, 4); (2, 2); (0, 0); (9, 9); (7, 7); (5, 5); (3, 3);
 (1, 1)]
```

**Comment by UnixJunkie** [comment]
I'm using parmap 1.0-rc9 from opam

**Comment by UnixJunkie** [comment]
the problem is caused by the ~chunksize of 1

**Comment by UnixJunkie** [comment]
fix here: https://github.com/rdicosmo/parmap/pull/75

**Comment by UnixJunkie** [comment]
please tell me when there is a new tag, we need to update the opam package with this bugfix

**Comment by rdicosmo** [comment]
Release done, and a *big* thanks.

--
Roberto

Le mar. 10 juil. 2018 à 11:09, UnixJunkie <notifications@github.com> a
écrit :

**Comment by UnixJunkie** [comment]
opam PR:
https://github.com/ocaml/opam-repository/pull/12337
Thanks for your quick action Roberto.
