### ISSUE TITLE
ocaml 4.08

### ISSUE THREAD

**Issue by JuliaLawall** [rdicosmo/parmap#84]
Apparently parmap doesn't work with ocaml 4.08.  Apparently Bigarray.Array1.map_file has disappeared.

**Comment by UnixJunkie** [comment]
We should use the stdcompat library to not be annoyed by such things.
There is a Unix.map_file in 4.08, if you need a quick workaround.

**Comment by UnixJunkie** [comment]
If you need a branch with the changes: https://github.com/rdicosmo/parmap/pull/85

I just hate when the stdlib changes. The stdlib should not be used outside of the compiler...

**Comment by XVilka** [comment]
Any updates on this one?

**Comment by UnixJunkie** [comment]
should be fixed.
the fixed version should appear in opam soon: https://github.com/ocaml/opam-repository/pull/14973
